# Generated by Django 4.0 on 2021-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('phone', models.BigIntegerField(null=True)),
                ('eid', models.CharField(max_length=30)),
            ],
        ),
    ]
